### PR TITLE
docs: update readme

### PR DESCRIPTION
**Pull request by stefanicjuraj**
Fixes https://github.com/daytonaio/enterprise-docs/issues/86

### CODE REVIEW

**Comment by ivan-burazin** [comment]
@stefanicjuraj and @nkkko why did we remove the structure part of the readme?

Felt that was usefull?

**Comment by stefanicjuraj** [comment]
Hi, if you are referring to the content structure, I haven't deleted it, I just renamed it to better fit the wording - 
https://github.com/daytonaio/enterprise-docs/pull/130/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R69

Let me know if this is what you meant.

**Comment by ivan-burazin** [comment]
Nope. @nkkko will no there was a filesystem view

**Comment by stefanicjuraj** [comment]
Found the commit where it was removed (during the refactor of the README) - https://github.com/daytonaio/enterprise-docs/commit/a51efe9cc8d2e16d5e69ee0af5c71c932677a418#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5.

I can add this back, and create for the oss documentation too. @ivan-burazin @nkkko

**Comment by nkkko** [comment]
I have no strong opinion on this. Could make sense to have it as it will be delivered with the product. But we need to ensure that it is kept updated.

**Review by ivan-burazin — APPROVED** [review]

**Review by fabjanvucina — APPROVED** [review]

**Pull request merged**
